services:
  php:
    restart: always
    build: ./php
    volumes:
      - ./src:/var/www/exment
    networks:
      - exment-net

  db:
    image: mariadb:10.11
    command: --skip-ssl
    environment:
      MYSQL_DATABASE: exment_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: exment_user
      MYSQL_PASSWORD: exment_password
    volumes:
      - exment-db-data:/var/lib/mysql
    networks:
      - exment-net
    restart: always

  web:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/exment
      - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - exment-net
      - proxy-net #サービス名で解決
    restart: always

networks:
  exment-net: # Exment内部通信用
  proxy-net:  # nginxporxyとの通信用
    external: true # 

volumes:
  exment-db-data:
